---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  namespace: odoo
  labels:
    app: odoo
    component: database
type: Opaque
stringData:
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: postgres
