#!/command/with-contenv bash
# shellcheck shell=bash
set -e

OPTIONS_SOURCE=${ADDON_DATA_FOLDER:-"/data"}/options.json
TZ_VAL=$(jq -r '.TZ // "Etc/UTC"' "$OPTIONS_SOURCE")

echo "Starting PostgreSQL ${PG_MAJOR} server..."

exec s6-setuidgid postgres postgres \
    -D "$PGDATA" \
    -c timezone="$TZ_VAL" \
    -c log_timezone="$TZ_VAL" \
    -c listen_addresses="localhost" \
    -c port=5432
